[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lightning_reference_module"
version = "0.0.1"
authors = [
  { name="Niels Bongers" },
]
description = "PyTorch Lightning reference code"
readme = "README.md"
requires-python = ">=3.10"

