run name: Rotation classification 
# root: "F://GSM Arena phone images//Sorted" 
root: "F://COCO//train2017"

model: "resnet50"

learning rate: 0.0005
gamma: 0.9 
max epochs: 10000000

accumulation steps: 2
real batch size: 64

# Classification and regression. 
# Set regression to Yes; number classes does not matter in that case. 
number classes: 4
regression: No 

save model: Yes 