run name: X-ray batteries
root: "C:/Users/Niels/My Drive/Python/Datasets/X-ray alkaline lithium-ion/organized"

model: "convnext"

learning rate: 0.0005
gamma: 0.9 
max epochs: 10000000

accumulation steps: 2
real batch size: 32

# Classification and regression. 
# Set regression to Yes; number classes does not matter in that case. 
number classes: 2
regression: No 

save model: No 