run name: Wisse battery test, more data
# root: "../Datasets/Ants vs bees"
root: 'D:\Google Drive\Python\Datasets\Battery classification\Wisse combined datasets\sorted' 

model: "resnet50"

learning rate: 0.0005
warmup epochs: 5
gamma: 0.9 
epochs: 1000 

desired batch size: 32
real batch size: 16

number classes: 3

only save best: Yes 
save model: Yes 
save all models: No 