run name: Example run
# root: "../Datasets/Ants vs bees"
root: "F:/X-ray datasets/HiXray/Sorted data test"

model: "resnet15"

learning rate: 0.0005
warmup epochs: 5
gamma: 0.9 
epochs: 1000 

desired batch size: 40
real batch size: 40

number classes: 2 

only save best: Yes 
save model: No 
save all models: No 