run name: Wisse battery test
# root: "../Datasets/Ants vs bees"
root: "../../Datasets/Battery classification/Wisse preliminary data/Sorted/alkaline_lithium_cropped"

model: "resnet50"

learning rate: 0.0005
warmup epochs: 5
gamma: 0.9 
epochs: 1000 

desired batch size: 32
real batch size: 16

number classes: 2 

only save best: Yes 
save model: No 
save all models: No 